### ISSUE TITLE
Add support for locally defined routes

### ISSUE THREAD

**Issue by xhenner** [pyke369/exabgp-helpers#12]
With exasrv, all routes are configured in the upstream routers.
You can still add a local static route, but with a fixed nexthop, which can be down

We need a configuration parameter to add some route in the fib, not announced by the peer, but which will be activated if and only if the peer is up, using the peer as nexthop

**Comment by xhenner** [comment]
Other configuration options needed : an option on a route to not import it when received
        "routes": {
            "0.0.0.0/0": {
                "import": 0
            }
       }

**Comment by pyke369** [comment]
For the second request, use: "ignore": True (see example configuration file).

**Comment by pyke369** [comment]
Fixed by 6f0ef23fb1f7ca63fda1ad1c6efed4544ba2866c
