### ISSUE TITLE
Remove VIP from loopback when healthcheck fails

### ISSUE THREAD

**Issue by ghost** [pyke369/exabgp-helpers#14]
(In some configurations, a single host may provide multiple services which can be failed over independently.  A VIP per service can be used but the health check currently handles all VIPs with a single health check. Would it be possible to implement health checks on a per VIP basis?)

Based on the above scenario there's another issue to be addressed.  If local service A depends on local service B and local service B fails, exasrv will stop announcing the VIP for service B, but the VIP remains on the local loopback interface.  It would be useful to be able to remove the VIP from the local loopback in the case of service B failing so that service A can still query service B via the VIP on healthy nodes in the cluster.

**Comment by pyke369** [comment]
The second par of this request was done in 59880911af1c. I'm closing this one, please open another one for the first part (which is a totally different beast IMHO...)
