### ISSUE TITLE
integrating this code into exa-networks/exabgp master ?

### ISSUE THREAD

**Issue by thomas-mangin** [pyke369/exabgp-helpers#4]
Hello Pierre-Yves,

If you are fine with the idea. This would complement the healthcheck script already in the code ( you should check it as it seems that there is some duplication of feature there too ).

I could also give you write access to the repository to allow you to keep the code up-to-date.
I think the code would need some tidying up but it should not take too long :smile:

Thomas

**Comment by pyke369** [comment]
Hello Thomas,

Yes, sure. Actually, I think exasrv is a superset of healthcheck somehow, b/c it does everything healthcheck does + generate exabgp configuration on the fly (it's necessary for us, the program being part of a larger SDN workflow) + programmatically controls the local host routing table. It also supports multiple peers groups with different options / VIPs and rely on a lax-JSON configuration file.

I still need to document it properly. Tell me what you have in mind re. "tidying up" the code :smile: 

Pierre-Yves

**Comment by thomas-mangin** [comment]
Pierre-Yves - closing as clearly none of us have the time to do that :-(
