### ISSUE TITLE
Support for BGP Communities and AS Path prepend in weight attribute for VIP

### ISSUE THREAD

**Issue by gootanoo** [pyke369/exabgp-helpers#5]
Hi, 

today when weight is set to primary, a MED of 100 is sent to the BGP peer. If the weight is set to secondary, a MED of 200 is sent to the BGP peer. It works great but to have more flexibility I propose to add 2 others methods.

Can you add the possibility to send a specific BGP community or prepend the AS PATH a certain number of times depending on the weight parameter (primary or secondary).

Thanks.

**Comment by pyke369** [comment]
Sure can. Although you could already specify a community or aspath in the VIP definition array. I will enhance the "weight" attribute syntax to automate that process.

**Comment by pyke369** [comment]
After some thoughts, won't fix (use the attributes already available).
