### ISSUE TITLE
Add a alwaysup atribute in service/addresses/<ip>

### ISSUE THREAD

**Issue by xhenner** [pyke369/exabgp-helpers#6]
At Dailymotion, we use exasrv for service and for basic access to servers

If we use the check or the disable directives, a service outage will disable the basic access too, which is not very practical.

The propose new configuration would be : 

```
    "service":
    {
        "addresses":
        {
            "192.0.2.1//32": { "weight": "primary", "alwaysup": true },
            "192.0.2.4/32": { "weight": "primary" },
            "192.0.2.5/32": { "weight": "secondary" }
        },
        "check":
        {
            "command": "/etc/exabgp/processes/check-service"
        },
        "disable": "/etc/exabgp/processes/service.disable"
    }
```

In this example, if we create /etc/exabgp/processes/service.disable or if /etc/exabgp/processes/check-service returns false, the IP .4 and .5 will disappear, but the .1 address will remain available

**Comment by pyke369** [comment]
Fixed in a3741a5.
