### ISSUE TITLE
Allow vip to be created on another interface

### ISSUE THREAD

**Issue by xhenner** [pyke369/exabgp-helpers#7]
At Dailymotion, we have a stupid software which refuse to acknowledge IP if they are on lo

Please add an option to the service/address configuration bloc to use another interface for the virtual IPs
No need to create the interface, it can be done at system level

Example : 

```
"service":
{
    "addresses":
    {
        "192.0.2.1//32": { "weight": "primary"},
        "192.0.2.4/32": { "weight": "primary", "interface": "eth0" },
        "192.0.2.5/32": { "weight": "secondary", "interface": "somebridge" }
    }
}
```

**Comment by pyke369** [comment]
Fixed in 1c5b135
